services:
  redis:
    image: redis:7-alpine
    container_name: defect-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

  mysql:
    # image: mysql:8.4
    image: mysql:8.0
    platform: linux/arm64
    container_name: defect-mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root_password}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-defect_ai}
      MYSQL_USER: ${MYSQL_USER:-app_user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-app_password}
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mysqladmin ping -h localhost -u$$MYSQL_USER -p$$MYSQL_PASSWORD",
        ]
      interval: 10s
      timeout: 5s
      retries: 10

  api:
    build:
      context: ./backend
      dockerfile: docker/Dockerfile.api

    container_name: defect-api

    ports:
      - "8000:8000"

    command: sh -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000"

    volumes:
      - ./backend:/app

    env_file:
      - ./backend/.env
    environment:
      REDIS_URL: redis://redis:6379/0
      DATABASE_URL: mysql+aiomysql://${MYSQL_USER:-app_user}:${MYSQL_PASSWORD:-app_password}@mysql:3306/${MYSQL_DATABASE:-defect_ai}

    depends_on:
      redis:
        condition: service_healthy
      mysql:
        condition: service_healthy

  worker:
    build:
      context: ./backend
      dockerfile: docker/Dockerfile.worker

    container_name: defect-worker
    command: rq worker detection

    volumes:
      - ./backend:/app

    env_file:
      - ./backend/.env
    environment:
      REDIS_URL: redis://redis:6379/0
      DATABASE_URL: mysql+aiomysql://${MYSQL_USER:-app_user}:${MYSQL_PASSWORD:-app_password}@mysql:3306/${MYSQL_DATABASE:-defect_ai}
      PYTHONPATH: /app
    depends_on:
      redis:
        condition: service_healthy
      mysql:
        condition: service_healthy

volumes:
  mysql_data:
