services:
  redis:
    image: redis:7-alpine
    container_name: defect-redis
    ports:
      - "6379:6379"

  api:
    build:
      context: ./backend
      dockerfile: docker/Dockerfile.api

    container_name: defect-api

    ports:
      - "8000:8000"

    volumes:
      - ./backend:/app

    env_file:
      - ./backend/.env

    depends_on:
      - redis

  worker:
    build:
      context: ./backend
      dockerfile: docker/Dockerfile.worker

    container_name: defect-worker

    volumes:
      - ./backend:/app

    env_file:
      - ./backend/.env

    depends_on:
      - redis
